_format_version: "3.0"
_plugin_configs: {}
# Template for Public/External APIs (mTLS + OIDC)
plugins:
  - name: mtls-auth
    config:
      anonymous: null
      ca_certificates:
        - "a1b2c3d4-e5f6-7890-1234-567890abcdef"
  - name: openid-connect
    config:
      issuer: "https://trial-4848815.okta.com/oauth2/default"
      client_id: []
      client_auth: []

ca_certificates:
  - id: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIFIzCCAwugAwIBAgIUMZS2+RZucpKUrxZ52Ml+AH4ALicwDQYJKoZIhvcNAQEL
      BQAwITEfMB0GA1UEAwwWS29uZ0FpciBTZWxmIFNpZ25lZCBDQTAeFw0yNTEyMjMw
      NTU4MjFaFw0yNjEyMjMwNTU4MjFaMCExHzAdBgNVBAMMFktvbmdBaXIgU2VsZiBT
      aWduZWQgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC0tvaGJhCx
      dgYIpfABAHBGHheflD6h/bqCvbolmIeSknrgSPyJhtl2uKFhoTT86WYF3bXvHeoV
      xmh9OzwIGuAvA7913aseUKxVygRLTpyTK176XMylgKdioL6utyv51TNjTR7LRlzL
      JYonGQHUED6Lc53mBDCg1MuGZQ1fCp5bD08YOQlfTSqZld55ir3H/SeSZlynTAdw
      ivlLjcBVp92BfVXN9WkmSp7MYAbrNoZfbE7UZblcfXi5ACv/OnNCqQFQuu9ScI/I
      yfniA4dhU0mbuQJeKLlTICDcga8VrqihirkRdZix+iVP1VZ/sUMHTm2MfbM51LKA
      Gbm+8rVaAmp5cwNLETtwvqPYgLMqnqrj4EOJx0Dikj+e5MCxqDM5/Gu4ER31ISEE
      hnt6ya0JicBKAQpu4Vd5YVkMU3fWtqKsN/F8kr+M4QI+YeJXk/Z7hjDypBVZ/TKf
      bH3rREFKPKthTS205zEwEuSqrYT8hLl8qhe+nPvrZtmQTy7dS43Ejwbe43J6HHkp
      ZAalrV7IN3VOgGHcUMyDOuJfskMrzHV1R9ul0ZGCPQAP8VNUHIza29Y4nYNMQPvv
      HciqkwlsVLa1wLcqSVTm78xaK+HOXgru5QBnKmB7d4qGa69EJkfIEy/NBs8+15GB
      6Jy3ELMbJ3MaEQTFXZvqUtqX+ou2fORmUwIDAQABo1MwUTAdBgNVHQ4EFgQUryrQ
      Y99O+QZhv9IMRTAQ+uUwivIwHwYDVR0jBBgwFoAUryrQY99O+QZhv9IMRTAQ+uUw
      ivIwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAmUQCzV42xOxp
      DVqPjlPdnvE1+jHz2bOCkJXFAjJ/jTfL5lWVZnh72NFaceQD9HYcq8QBIMOQK/io
      B7kejIMjvQpNpd+xgOI6ipvsYRxhC4xlMnvv1rFEGL81tJ4den8pgrjZNO3a1xPX
      TXrCm9omXERnpJ+jWbiYu9m78NRrj2XB1+qtXJZ4QiLYwtebhUJ6XGh30/RgODVy
      aJmOczZ+cOcSJILC17TT1wi3XhFNHTBhZ0Bc3TKEhNJapXfX7YIiY1zDE7RkhGOY
      TODmL68P+w7UL9hllF5LrAhAUxymtQbSCR3sm6op4hzpHMQA/j2HlxIdVuynOhso
      JYrxbs/DYkU0/dPftaxeensQ9lWbmPUw1sIkNL1rlFwbCwCi+x8TJj0Tf/OdpTrE
      XStnACXzJtWm7MIwnOtjugxA9h9hVtUiMUMCiXccV/P4xonh5au1IPteCyTH94IE
      E26frq6FFxPkyvRFYmlL1agCTqCIHVMGf8QSztXAUDqOkjDQze5gy1GKLd6ogyK2
      2VVdYqBmP5FI2Yc3JshcOkzPzWKT6RWik2EqmKtyV4alQ1bfqOkGfiIpVAm8kTE7
      SyawMYUwTYCjCUdULkZrUvRfEEtl6lnDkOBcI6rL/4z29RtJavNb5uaZIALQvRFP
      snZ19UTkx0ouUZ1uksVteApgygbnZAs=
      -----END CERTIFICATE-----

